# Base model configuration
base_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_type: LlamaForCausalLM
trust_remote_code: true
device_map: auto

# CPU-only setup (no quantization)
load_in_8bit: false
load_in_4bit: false
gptq: false

# Dataset configuration
datasets:
  - path: ./data/training.jsonl
    type: json

dataset_prepared_path: ./data/processed
val_set_size: 0.05

# LoRA (QLoRA) configuration
adapter: qlora
lora_r: 8
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

# Tokenizer & sequence
sequence_len: 2048
pad_to_sequence_len: true
sample_packing: false
train_on_inputs: false

# Training setup for CPU (minimal memory)
gradient_checkpointing: true
gradient_accumulation_steps: 4
batch_size: 4
micro_batch_size: 1
num_epochs: 3
optimizer: adamw
lr_scheduler: cosine
learning_rate: 2e-5
max_grad_norm: 1.0
weight_decay: 0.01
warmup_steps: 10

# Logging and saving
logging_steps: 5
save_steps: 100
save_total_limit: 2

# Output model
output_dir: ./model/final-checkpoint

# Evaluation
evals_per_epoch: 1
eval_table_size: 5
