# Model configuration
base_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_type: LlamaForCausalLM

# CPU/RAM-only setup (no GPU)
load_in_8bit: false
load_in_4bit: true
gptq: false
trust_remote_code: true
device_map: auto

# Dataset setup
datasets:
  - path: ./data/training.jsonl
    type: json

dataset_prepared_path: ./data/processed
val_set_size: 0.05

# LoRA / QLoRA config
adapter: qlora
lora_r: 8
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

# Tokenization & input length
sequence_len: 2048
sample_packing: false
pad_to_sequence_len: true
train_on_inputs: false

# Training optimization for low resource (CPU-only)
gradient_checkpointing: true
gradient_accumulation_steps: 2
batch_size: 2
micro_batch_size: 1
num_epochs: 3
optimizer: adamw
lr_scheduler: cosine
learning_rate: 2e-5

# Output
output_dir: ./model/final-checkpoint

# Logging
logging_steps: 5
save_steps: 100
save_total_limit: 2

# Evaluation
evals_per_epoch: 1
eval_table_size: 5
