base_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_type: LlamaForCausalLM
trust_remote_code: true
device_map: auto

load_in_8bit: false
load_in_4bit: true # ✅ requis avec QLoRA
gptq: false

datasets:
  - path: ./data/training.jsonl
    type: json

dataset_prepared_path: ./data/processed
val_set_size: 0.05

adapter: qlora
lora_r: 8
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

sequence_len: 2048
pad_to_sequence_len: true
sample_packing: false
train_on_inputs: false

gradient_checkpointing: true
gradient_accumulation_steps: 4
micro_batch_size: 1

num_epochs: 3
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 2e-5
max_grad_norm: 1.0
weight_decay: 0.01
warmup_steps: 10

logging_steps: 5
save_steps: 100
save_total_limit: 2
output_dir: ./model/final-checkpoint

evals_per_epoch: 1
eval_table_size: 5

special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  pad_token: "<pad>"

logging_dir: ./logs
save_strategy: steps
